### ISSUE TITLE
Package versions missing in next_sentence

### ISSUE THREAD

**Issue by bkbroz** [GFNOrg/gfn-lm-tuning#9]
When trying to run:

python train.py task=open_webtext_gpt2 device=gpu

I get the following error:

Traceback (most recent call last):
  File "/workspace/gfn-lm-tuning/next_sentence/train.py", line 19, in <module>
    from lightning_data import PromptDataModule
  File "/workspace/gfn-lm-tuning/next_sentence/lightning_data.py", line 2, in <module>
    from torchdata.datapipes.map import MapDataPipe
  File "/usr/local/lib/python3.10/dist-packages/torchdata/datapipes/__init__.py", line 11, in <module>
    from . import iter, map, utils
  File "/usr/local/lib/python3.10/dist-packages/torchdata/datapipes/iter/__init__.py", line 79, in <module>
    from torchdata.datapipes.iter.util.cacheholder import (
  File "/usr/local/lib/python3.10/dist-packages/torchdata/datapipes/iter/util/cacheholder.py", line 24, in <module>
    from torch.utils._import_utils import dill_available
ModuleNotFoundError: No module named 'torch.utils._import_utils'

I think this is due to a dependency issue, since the packages in the requirements.txt doesn't have the version numbers. 
Please run 
pip freeze > requirements.txt

**Comment by MJ10** [comment]
Hi @bkbroz sorry for the delayed response. Here is the requirements.txt 
[requirements.txt](https://github.com/user-attachments/files/17636017/requirements.txt)
